name: Metrics

on:
  schedule:
    - cron: '0 */12 * * *'   # roda a cada 12h
  workflow_dispatch:          # permite rodar manualmente pelo Actions

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # ---- tema hacker/terminal (minimalista) ----
          config_timezone: America/Sao_Paulo
          base: header, activity
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size

          config_display: large
          config_theme: dark
