# .github/workflows/metrics.yml (VERSÃO CORRIGIDA DE VERDADE)

name: GitHub Metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu nome de usuário
          user: arthurSchgg
          
          # Token automático
          token: ${{ secrets.GITHUB_TOKEN }}

          # Nome do arquivo de saída
          filename: metrics.svg
          
          # --- A CORREÇÃO ESTÁ AQUI ---
          # Este é o layout que você quer (da imagem do "Gabriel Ehrat")
          base: header, activity, community, repositories
          
          # A linha 'config_theme' estava causando o Warning.
          # Removemos ela por enquanto.
